
[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "8.0.0"

[[constraint]]
  name = "github.com/emicklei/go-restful-swagger12"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  name = "github.com/peterbourgon/diskv"
  version = "2.0.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.8.4"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apimachinery"

# carolynvs: This is a transitive constraint that fixes https://github.com/kubernetes/client-go/issues/298
# It only works with a prototype of dep that allows transitive constraints
[[constraint]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"
