
[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "8.0.0"

[[constraint]]
  name = "github.com/emicklei/go-restful-swagger12"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  name = "github.com/peterbourgon/diskv"
  version = "2.0.1"

[[constraint]]
  branch = "release-1.7"
  name = "k8s.io/apimachinery"