
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/coreos/go-oidc"

[[constraint]]
  name = "github.com/davecgh/go-spew"

[[constraint]]
  name = "github.com/docker/distribution"

[[constraint]]
  name = "github.com/emicklei/go-restful"

[[constraint]]
  name = "github.com/ghodss/yaml"

[[constraint]]
  name = "github.com/gogo/protobuf"

[[constraint]]
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/golang/groupcache"

[[constraint]]
  name = "github.com/google/gofuzz"

[[constraint]]
  name = "github.com/howeyc/gopass"

[[constraint]]
  name = "github.com/imdario/mergo"

[[constraint]]
  name = "github.com/juju/ratelimit"

[[constraint]]
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/ugorji/go"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "k8s.io/apimachinery"
